console/views/FTP.py
import base64
import logging.handlers

import flask_security
from flask import Blueprint, render_template
from structlog import wrap_logger

from console.console_ftp import ConsoleFtp, PATHS

logger = wrap_logger(logging.getLogger(__name__))

FTP_bp = Blueprint('FTP_bp', __name__, static_folder='static', template_folder='templates')


def get_file_contents(datatype, filename):
    with ConsoleFtp() as ftp:
        return ftp.get_file_contents(datatype, filename)


@FTP_bp.route('/FTP', methods=['POST', 'GET'])
@flask_security.login_required
def ftp_home():
    with ConsoleFtp() as ftp:
        contents = ftp.get_folder_contents(PATHS["pck"])[0:20]
    return render_template('FTP.html', contents=contents)


@FTP_bp.route('/FTP/<datatype>', methods=['POST', 'GET'])
@flask_security.login_required
def ftp_pcks(datatype):
    if datatype not in ['pck', 'image', 'index', 'receipt', 'json']:
        return render_template('FTP.html')

    with ConsoleFtp() as ftp:
        contents = ftp.get_folder_contents(PATHS[datatype])[0:20]
    return render_template('FTP.html', contents=contents)


@FTP_bp.route('/view/<datatype>/<filename>')
@flask_security.login_required
def view_file(datatype, filename):
    if filename.lower().endswith(('jpg', 'png')):
        extension = filename.split(".")[-1]
        b64_image = base64.b64encode(get_file_contents(datatype, filename)).decode()
        return '<img style="width:100%;" src="data:image/' + extension + ';base64,' + b64_image + '" />'
    else:
        return '<pre>' + get_file_contents(datatype, filename).decode("utf-8") + '</pre>'

console/views/SEFT.py
import logging.handlers
import time
import uuid
import yaml
import base64
import os

import flask_security
from flask import Blueprint, render_template, request
from structlog import wrap_logger
from sdc.rabbit import QueuePublisher
from sdc.rabbit.exceptions import PublishMessageError
from sdc.crypto.encrypter import encrypt
from sdc.crypto.key_store import KeyStore

import console.settings as settings

logger = wrap_logger(logging.getLogger(__name__))

SEFT_bp = Blueprint('SEFT_bp', __name__, static_folder='static', template_folder='templates')


def send_payload(payload, tx_id):
    logger.info("About to send SEFT payload", tx_id=tx_id)

    publisher = QueuePublisher(settings.RABBIT_URLS, settings.SEFT_CONSUMER_RABBIT_QUEUE)
    try:
        publisher.publish_message(payload, headers={'tx_id': tx_id})
    except PublishMessageError:
        logger.exception("Failed to put SEFT payload on queue", tx_id=tx_id)

    logger.info("SEFT payload successfully placed onto rabbit queue", tx_id=tx_id)


def convert_file_object_to_string_base64(file):
    """
    Convert a file object to a string
    :param file: The file to convert
    :return: String
    """
    return base64.b64encode(file).decode()


@SEFT_bp.route('/SEFT', methods=['GET', 'POST'])
@flask_security.login_required
def get_seft():
    messages = []
    if request.method == 'POST':
        seft_file = request.files['file']
        if seft_file.filename == '':
            messages.append('No selected file')
            logger.info("No selected file")
        _, file_extension = os.path.splitext(seft_file.filename)
        if file_extension not in ['.xls', '.xlsx']:
            messages.append('Incorrect file extension')
            logger.info("Incorrect file extension")

        if messages:
            return render_template('SEFT.html', messages=messages)

        tx_id = str(uuid.uuid4())
        case_id = str(uuid.uuid4())
        ru_ref = "12345678901A"
        # The submission will be put into a folder of the same name in the FTP server
        survey_ref = "survey_ref"

        _, file_extension = os.path.splitext(seft_file.filename)
        file_as_string = convert_file_object_to_string_base64(seft_file.stream.read())

        time_date_stamp = time.strftime("%Y%m%d%H%M%S")
        file_name = "{ru_ref}_{exercise_ref}_" \
                    "{survey_ref}_{time_date_stamp}{file_format}".format(ru_ref=ru_ref,
                                                                         exercise_ref="exercise_ref",
                                                                         survey_ref=survey_ref,
                                                                         time_date_stamp=time_date_stamp,
                                                                         file_format=file_extension)

        logger.info("Generated filename for file going to FTP", file_name=file_name, case_id=case_id, tx_id=tx_id)
        message_json = {
            'filename': file_name,
            'file': file_as_string,
            'case_id': case_id,
            'survey_id': survey_ref
        }

        with open("./seft-keys.yml") as file:
            secrets_from_file = yaml.safe_load(file)

        key_store = KeyStore(secrets_from_file)
        payload = encrypt(message_json, key_store, 'inbound')

        send_payload(payload, tx_id)
        messages.append('File queued successfully')

    return render_template('SEFT.html', messages=messages)

console/views/add_user.py
import logging

from flask import Blueprint
from flask import render_template
from flask import request
import flask_security
from structlog import wrap_logger

from console.forms import NewUserForm
from console.helpers.exceptions import UserCreationError, UserExistsError
from console.models import create_dev_user

logger = wrap_logger(logging.getLogger(__name__))

add_user_bp = Blueprint('add_user_bp', __name__, static_folder='static', template_folder='templates')


@add_user_bp.route('/add_user', strict_slashes=False, methods=['GET', 'POST'])
@flask_security.login_required
@flask_security.roles_required('Admin')
def add_user():
    form = NewUserForm()
    if request.method == 'POST' and form.validate():
        success = False
        try:
            create_dev_user(form.email.data, form.password.data)
            success = True
        except UserCreationError:
            form.errors['Database'] = ["Error creating user"]
        except UserExistsError:
            form.errors['User'] = ["This user already exists"]

        return render_template('add_user.html', form=form, success=success, user=form.email.data)

    else:
        return render_template('add_user.html', form=form)

console/views/logout.py
import logging

from flask import Blueprint
from flask import jsonify
from flask import render_template
import flask_security
from structlog import wrap_logger

from console.helpers.exceptions import ResponseError

logger = wrap_logger(logging.getLogger(__name__))

logout_bp = Blueprint('logout_bp', __name__, static_folder='static', template_folder='templates')


@logout_bp.route('/logout', strict_slashes=False, methods=['GET', 'POST'])
def logout():
    flask_security.utils.logout_user()
    return render_template('logout.html')


@logout_bp.errorhandler(ResponseError)
def handle_invalid_usage(error):
    json_error = {"message": error.message, "status_code": error.status_code}
    return jsonify(json_error)

console/views/store.py
import json
import logging

from datetime import datetime
from flask import Blueprint
from flask import render_template
from flask import request
import flask_security
from sqlalchemy import func
from sqlalchemy.exc import DataError
from sqlalchemy.exc import SQLAlchemyError
from structlog import wrap_logger

from console import settings
from console.forms import StoreForm
from console.models import SurveyResponse
from console.views.submit import send_data
from sdc.rabbit import QueuePublisher

logger = wrap_logger(logging.getLogger(__name__))

store_bp = Blueprint('store_bp', __name__, static_folder='static', template_folder='templates')

TRANSACTIONS_PER_PAGE = 20


def get_filtered_responses(logger, valid, tx_id, ru_ref, survey_id, datetime_earliest, datetime_latest, page_num):
    logger.info('Retrieving responses from sdx-store')
    try:
        q = SurveyResponse.query

        if valid == "invalid":
            q = q.filter(SurveyResponse.invalid)
        elif valid == "valid":
            #  NOQA comment is used because == False is the correct syntax, but flake8 disagrees
            q = q.filter(SurveyResponse.invalid == False)  # NOQA
        if tx_id != '':
            q = q.filter(SurveyResponse.tx_id == tx_id)
        if ru_ref != '':
            q = q.filter(SurveyResponse.data["metadata"]["ru_ref"].astext == ru_ref)
        if survey_id != '':
            q = q.filter(SurveyResponse.data["survey_id"].astext == survey_id)
        dt_column = func.date(SurveyResponse.data["submitted_at"].astext)
        if datetime_earliest:
            year = int(datetime_earliest[:4])
            month = int(datetime_earliest[5:7])
            day = int(datetime_earliest[8:10])
            q = q.filter(dt_column > datetime(year, month, day))
        if datetime_latest:
            year = int(datetime_latest[:4])
            month = int(datetime_latest[5:7])
            day = int(datetime_latest[8:10])
            q = q.filter(dt_column < datetime(year, month, day))
        filtered_data = q.paginate(per_page=TRANSACTIONS_PER_PAGE, page=page_num, error_out=True)

    except DataError:
        logger.exception("Invalid search term")
        return []
    except SQLAlchemyError:
        logger.exception("Database error")
        return []

    return filtered_data


def reprocess(tx_id):
    logger.info('Reprocessing submission', tx_id=tx_id)
    publisher = QueuePublisher(settings.RABBIT_URLS, 'sdx_downstream')
    publisher.publish_message(tx_id, headers={'tx_id': tx_id})
    logger.info('Successfully reprocessed submission', tx_id=tx_id)


@store_bp.route('/reprocess', strict_slashes=False, methods=['POST'])
@flask_security.login_required
def reprocess_submission():
    tx_ids = request.form.getlist('reprocess-tx_id')
    data = []
    for tx_id in tx_ids:
        data.append(tx_id)
        reprocess(tx_id)
    logger.info('Finished reprocessing submissions', no_of_submissions=len(tx_ids))

    return render_template('reprocess.html', data=data)


@store_bp.route('/store', strict_slashes=False, methods=['GET'])
@flask_security.login_required
def store_home():
    return render_template('store.html',
                           current_user=flask_security.core.current_user,
                           form=StoreForm())


@store_bp.route('/store/page/<int:page_num>', strict_slashes=False, methods=['GET'])
@flask_security.login_required
def store(page_num):
    audited_logger = logger.bind(user=flask_security.core.current_user.email)
    valid = request.args.get('valid', type=str, default='')
    tx_id = request.args.get('tx_id', type=str, default='')
    ru_ref = request.args.get('ru_ref', type=str, default='')
    survey_id = request.args.get('survey_id', type=str, default='')
    datetime_earliest = request.args.get('datetime_earliest', type=str, default='')
    datetime_latest = request.args.get('datetime_latest', type=str, default='')
    search_query = {
        "tx_id": tx_id,
        "ru_ref": ru_ref,
        "survey_id": survey_id,
        "datetime_earliest": datetime_earliest,
        "datetime_latest": datetime_latest
    }

    # These two variables are either empty, or datetime objects.  A separate variable had
    # to be used as we need the string representation of the date for the database filter and a
    # datetime representation of the date for the StoreForm object.
    datetime_earliest_value = None
    datetime_latest_value = None
    if datetime_earliest:
        datetime_earliest_value = datetime.strptime(datetime_earliest, '%Y-%m-%d')
    if datetime_latest:
        datetime_latest_value = datetime.strptime(datetime_latest, '%Y-%m-%d')

    form = StoreForm(
        valid=valid,
        tx_id=tx_id,
        ru_ref=ru_ref,
        survey_id=survey_id,
        datetime_earliest=datetime_earliest_value,
        datetime_latest=datetime_latest_value
    )

    if form.validate():
        pagnated_store_data = get_filtered_responses(
            audited_logger, valid, tx_id, ru_ref, survey_id, datetime_earliest, datetime_latest, page_num)
    else:
        pagnated_store_data = []

    audited_logger.info("Successfully retrieved responses")

    audited_logger.info("Search query: {}".format(search_query))

    return render_template('store_data.html',
                           data=pagnated_store_data,
                           search_query=search_query,
                           current_user=flask_security.core.current_user,
                           form=form)


@store_bp.route('/storetest', strict_slashes=False, methods=['GET'])
@flask_security.login_required
def storetest():
    def create_test_data(number):
        test_data = json.dumps(
            {
                "collection": {
                    "exercise_sid": "hfjdskf",
                    "instrument_id": "ce2016",
                    "period": "0616"
                },
                "data": {
                    "1": "2",
                    "2": "4",
                    "3": "2",
                    "4": "Y"
                },
                "metadata": {
                    "ru_ref": "12345678901a",
                    "user_id": "789473423"
                },
                "origin": "uk.gov.ons.edc.eq",
                "submitted_at": "2017-04-27T14:23:13+00:00",
                "survey_id": "1",
                "tx_id": "f088d89d-a367-876e-f29f-ae8f1a26" + str(number),
                "type": "uk.gov.ons.edc.eq:surveyresponse",
                "version": "0.0.1"
            })
        return test_data

    for i in range(1000, 1250):
        test_data = create_test_data(str(i))
        send_data(logger=logger,
                  url=settings.SDX_STORE_URL,
                  data=test_data,
                  request_type="POST")

    return "data sent"

console/views/submit.py
import json
import logging.handlers
import os
import uuid

import flask_security
import requests
import yaml
from flask import Blueprint
from flask import jsonify
from flask import render_template
from flask import request
from structlog import wrap_logger

import console.settings as settings
from console.helpers.exceptions import ClientError, ServiceError
from sdc.crypto.encrypter import encrypt
from sdc.crypto.key_store import KeyStore
from sdc.rabbit import QueuePublisher

logger = wrap_logger(logging.getLogger(__name__))

submit_bp = Blueprint('submit_bp', __name__, static_folder='static', template_folder='templates')


def list_surveys():
    return sorted([f for f in os.listdir('console/static/surveys') if os.path.isfile(os.path.join('console/static/surveys', f))])


def send_payload(payload, tx_id, no_of_submissions=1):
    logger.info("Sending encrypted Payload", tx_id=tx_id)

    publisher = QueuePublisher(settings.RABBIT_URLS, settings.RABBIT_QUEUE)
    for _ in range(no_of_submissions):
        publisher.publish_message(payload, headers={'tx_id': tx_id})

    logger.info("Sent Payload to rabbitmq", tx_id=tx_id)


def send_data(logger, url, data=None, json=None, request_type="POST"):
    response_logger = logger.bind(url=url)
    try:
        if request_type == "POST":
            response_logger.info("Sending POST request")
            if data:
                r = requests.post(url, data=data)
            elif json:
                r = requests.post(url, json=json)
        elif request_type == "GET":
            response_logger.info("Sending GET request")
            r = requests.get(url)
    except requests.exceptions.ConnectionError as e:
        response_logger.error("Failed to connect to service", response="Connection error")
        raise e

    if 199 < r.status_code < 300:
        logger.info('Returned from service', response=r.reason, status_code=r.status_code)
    elif 399 < r.status_code < 500:
        logger.error('Returned from service', response=r.reason, status_code=r.status_code)
        raise ClientError(url=url, message=r.reason, status_code=r.status_code)
    elif r.status_code > 499:
        logger.error('Returned from service', response=r.reason, status_code=r.status_code)
        raise ServiceError(url=url, message=r.reason, status_code=r.status_code)

    return r


@submit_bp.route('/submit', methods=['POST', 'GET'])
@flask_security.login_required
def submit():
    if request.method == 'POST':
        data = request.get_data().decode('UTF8')

        logger.info("Encrypting data")

        unencrypted_json = json.loads(data)

        no_of_submissions = int(unencrypted_json['quantity'])

        with open("./keys.yml") as file:
            secrets_from_file = yaml.safe_load(file)

        key_store = KeyStore(secrets_from_file)

        tx_id = unencrypted_json['survey']['tx_id']

        for _ in range(0, no_of_submissions):
            # If submitting more than one then randomise the tx_id
            if tx_id is None:
                tx_id = str(uuid.uuid4())
                unencrypted_json['survey']['tx_id'] = tx_id
                logger.info("Auto setting tx_id", tx_id=tx_id)

            payload = encrypt(unencrypted_json['survey'], key_store, 'submission')
            send_payload(payload, tx_id, 1)  # let the loop handle the submission

        return data
    else:
        return render_template('submit.html')


@submit_bp.route('/validate', methods=['POST', 'GET'])
@flask_security.login_required
def validate():
    if request.method == 'POST':
        payload = request.get_data()

        logger.info("Validating json", url=settings.SDX_VALIDATE_URL)
        r = requests.post(settings.SDX_VALIDATE_URL, data=payload)
        r.raise_for_status()
        logger.info("Successfully validated json", url=settings.SDX_VALIDATE_URL)
        return jsonify(json.loads(r.text))
    else:
        logger.info('Failed validation')
        return render_template('submit.html')


@submit_bp.route('/surveys')
def surveys():
    return json.dumps(list_surveys(), indent=4)

console/templates/FTP.html
{% import 'partials/section.html' as section %}
{% extends "layouts/_twocol.html" %}

{% block page_title %} FTP {% endblock %}


{% block content %}

  {% include 'partials/navigation_tabs.html' %}

  <div class="container">

    {% include 'partials/receiver.html' %}

    {% include 'partials/modal.html' %}

  </div>

{% endblock content %}

console/templates/SEFT.html
{% import 'partials/section.html' as section %}
{% extends "layouts/_twocol.html" %}

{% block page_title %} SEFT {% endblock %}


{% block content %}

  {% include 'partials/navigation_tabs.html' %}

  <div class="container">
    <ul>
    {% for message in messages %}
      <li>{{ message }}</li>
    {% endfor %}
    </ul>
    <form method=POST enctype=multipart/form-data>
      <input type="file" name="file">
      <input type="submit" value="Upload">
    </form>
  </div>

{% endblock content %}

console/templates/add_user.html
{% import 'partials/section.html' as section %}
{% extends "layouts/_twocol.html" %}

{% block page_title %} Add User {% endblock %}


{% block content %}

{% include 'partials/navigation_tabs.html' %}

<div class="container">
  <div class="row">

    <div class="col-sm-6">
      <form class="form-group" action="/add_user" method="POST">
        <h2>Add a new SDX developer user</h2>
        <p>
          Please enter an email for the user:<br>
          {{ form.email }}<br>
        </p>
        <p>
          Please enter a password for the user:<br>
          {{ form.password }}<br>
        </p>
        {% if form.errors %}
            <ul class=errors>
            {% for error in form.errors %}
              <li>{{error}} : {{ form.errors[error][0] }}</li>
            {% endfor %}
            </ul>
        {% endif %}

        <input value="Add User" class="btn btn-default" type="submit"><br>
      </form>

      <br>
      {% if success %}
        Added new user {{user}}
      {% endif %}
    </div>

  </div>
</div>

{% endblock content %}

console/templates/adduser.html
{% extends "layout.html" %}
{% set active_page = "AddUser" %}
{% block body %}

<div class='container'>
  <div class="row">

    <div class="col-sm-6">
      <form class="form-group" action="/adduser" method="POST">
        <h3>Add a new SDX developer user</h3><br>
        <p>
          Please enter an email for the user:<br>
          {{ form.email(size=100) }}<br>
        </p>
        <p>
          Please enter a password for the user:<br>
          {{ form.password }}<br>
        </p>
        {% if form.errors %}
            <ul class=errors>
            {% for error in form.errors %}
              <li>{{error}} : {{ form.errors[error][0] }}</li>
            {% endfor %}
            </ul>
        {% endif %}

        <input value="Add User" class="btn btn-default" type="submit"><br>
      </form>

      <br>
      {% if success %}
        Added new user {{user}}
      {% endif %}
    </div>

  </div>
</div>

{% endblock %}

console/templates/logout.html
{% import 'partials/section.html' as section %}
{% extends "layouts/_twocol.html" %}

{% block page_title %} Logout {% endblock %}


{% block content %}

{% include 'partials/navigation_tabs.html' %}

<div class="container">
  <div class="row">
    <div class="col-sm-6">
      {% if current_user.is_authenticated %}
        <h3>Logged in as: {{current_user.email}}</h3>
      {% else %}
        You have been logged out.<br>
        To use this service you need to
        <a href="{{ url_for('security.login', next='submit')}}"> log in</a>
      {% endif %}
    </div>
  </div>
</div>

{% endblock content %}

console/templates/reprocess.html
{% import 'partials/section.html' as section %}
{% extends "layouts/_twocol.html" %}

{% block page_title %} Reprocess {% endblock %}


{% block content %}

{% include 'partials/navigation_tabs.html' %}

<h1>The following transactions have been reprocessed</h1> <br>

  <table class="table" width="100%">
    <thead class="table__head table__header-cell--align">
      <tr>
        <th class="table__header-cell table__header-cell--align"> tx_id </th>
      </tr>
    </thead>

    {% if data %}
      <tbody>
        {% for tx_id in data %}
          <tr class="table__row">
            <td class="table__cell"> {{ tx_id }} </td>
          </tr>
        {% endfor %}
      </tbody>
    {% else %}
      <tbody>
          <tr class="table__row">
            <td class="table__cell"> Failed to retrieve tx_ids </td>
          </tr>
      </tbody>
    {% endif %}
  </table>

{% endblock content %}

console/templates/store.html
{% import 'partials/section.html' as section %}
{% extends "layouts/_twocol.html" %}

{% block page_title %} Store {% endblock %}


{% block content %}

{% include 'partials/navigation_tabs.html' %}

<div class="container">
  <div class="col-xs-12">
    <form id='store-form' class="form-horizontal" action='/store/page/1'>
      <div class="form-group">
        <div class="col-md-11">
          <div class="input-group">
            <label class="col-md-1 control-label" for="valid">Valid:</label>
            {% for subfield in form.valid %}
              <tr>
                <td>{{ subfield }}</td>
                <td>{{ subfield.label }}</td>
              </tr>
            {% endfor %}<br> <br>

            <label class="col-md-1 control-label" for="tx_id">tx_id:</label> <br>
            {{ form.tx_id }}<br>

            <label class="col-md-1 control-label" for="ru_ref">ru_ref:</label> <br>
            {{ form.ru_ref }}<br>

            <label class="col-md-1 control-label" for="survey_id">survey_id:</label> <br>
            {{ form.survey_id }}<br> <br>

            <label class="col-md-1 control-label" for="datetime_earliest">datetime_earliest: </label>
            {{ form.datetime_earliest }}<br>

            <label class="col-md-1 control-label" for="datetime_latest">datetime_latest: </label>
            {{ form.datetime_latest }}<br> <br>

          </div>

          <span class="input-group-btn">
              <button class="btn btn-default" type="submit">Search</button>
          </span>
          {% if form.errors %}
              <ul class=errors>
              {% for error in form.errors %}
                <li>{{error}} : {{ form.errors[error][0] }}</li>
              {% endfor %}
              </ul>
          {% endif %}
        </div>
      </div>
    </form>
  </div>
</div>
{% endblock content %}

console/templates/store_data.html
{% import 'partials/section.html' as section %}
{% extends "layouts/_twocol.html" %}

{% block page_title %} Store data {% endblock %}

{% block content %}

{% include 'partials/navigation_tabs.html' %}

<div class="container">
  <h1>Search results for:</h1>
    <h2>
      {% if search_query.tx_id %} <br> tx_id: {{ search_query.tx_id }} {% endif %}
      {% if search_query.survey_id %} <br> survey_id: {{ search_query.survey_id }} {% endif %}
      {% if search_query.ru_ref %} <br> ru_ref: {{ search_query.ru_ref }} {% endif %}
      {% if search_query.datetime_earliest %} <br> datetime_earliest: {{ search_query.datetime_earliest }} {% endif %}
      {% if search_query.datetime_latest %} <br> datetime_latest: {{ search_query.datetime_latest }} {% endif %}
    </h2>
    <br>

    <div class="table">
      <table class="table" width="100%">
        <thead class="table__head table__header-cell--align">
          <tr>
            <th class="table__header-cell table__header-cell--align"> tx_id </th>
            <th class="table__header-cell"> survey_id </th>
            <th class="table__header-cell"> ru_ref </th>
            <th class="table__header-cell"> user_id </th>
            <th class="table__header-cell"> submitted_at </th>
            <th class="table__header-cell"> invalid </th>
            <th class="table__header-cell" style="text-align: center;"> Reprocess <input type="checkbox" onchange="checkAll(this)" name="chk[]" /> </th>
          </tr>
        </thead>
        <tbody>
          <form id="reprocess-form" name='reprocess-form' class="form-horizontal" method='POST' action="/reprocess">
            {% if data %}
              {% for item in data.items %}
                <tr class="table__row">
                <td class="table__cell">{{ item.data.tx_id }}</td>
                <td class="table__cell">{{ item.data.survey_id }}</td>
                <td class="table__cell">{{ item.data.metadata.ru_ref }}</td>
                <td class="table__cell">{{ item.data.metadata.user_id }}</td>
                <td class="table__cell">{{ item.data.submitted_at }}</td>
                <td class="table__cell">{{ item.data.invalid }}</td>
                <td class="table__cell" style="text-align: center;">
                  <input type="checkbox" name="reprocess-tx_id" value="{{ item.data.tx_id }}">
                </td>
                </tr>
              {% endfor %}

              {% for page in data.iter_pages(left_edge=3, right_edge=3, left_current=3, right_current=3) %}
                {% if page %}
                  {% if page != data.page %}
                    <a href="{{ url_for('store_bp.store', page_num=page) }}?{{request.query_string.decode()}}">{{ page }} </a>
                  {% else %}
                    <strong> {{ page }} </strong>
                  {% endif %}
                {% else %}
                  <span class=ellipsis>…</span>
                {% endif %}
              {% endfor %}
            {% else %}
              <tbody>
                  <tr class="table__row">
                    <td class="table__cell"> Failed to retrieve data </td>
                  </tr>
              </tbody>
            {% endif %}
          </form>
        </tbody>
      </table>
      <br>
      <button class="btn btn-primary" form="reprocess-form" type="submit" style="float: right;">Reprocess</button>
    </div>
</div>
{% endblock content %}

console/templates/submit.html
{% import 'partials/section.html' as section %}
{% extends "layouts/_twocol.html" %}

{% block page_title %} Submit {% endblock %}


{% block content %}

{% include 'partials/navigation_tabs.html' %}

<div class="container">

  {% include 'partials/submitter.html' %}

  <div class="alert hidden alert-danger" role="alert" style="overflow: auto">
    <div class="alert hidden alert-danger panel__body" role="alert">
      <div class="alert hidden alert-danger" role="alert">
      </div>
    </div>
  </div>

</div>

{% endblock content %}